-- Crear tabla para civilizaciones
CREATE TABLE civilizacion (
    id NUMBER(10) default 1 PRIMARY KEY NOT NULL,
    nombre VARCHAR2(50) NOT NULL
);

-- Crear tabla para inventario
CREATE TABLE inventario (
    id_civilizacion NUMBER(10) PRIMARY KEY NOT NULL,
    madera NUMBER(10) DEFAULT 0,
    hierro NUMBER(10) DEFAULT 0,
    mana NUMBER(10) DEFAULT 0,
    comida NUMBER(10) DEFAULT 0,
    victorias NUMBER(4) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_inventario FOREIGN KEY (id_civilizacion)
    REFERENCES civilizacion(id)
    ON DELETE CASCADE
);

-- Crear tabla para edificios
CREATE TABLE edificios (
    id_civilizacion NUMBER(10) PRIMARY KEY NOT NULL,
    herreria NUMBER(10) DEFAULT 0, 
    granja NUMBER(10) DEFAULT 0,
    carpinteria NUMBER(10) DEFAULT 0,
    torre_magica NUMBER(10) DEFAULT 0, 
    iglesia NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_edificios FOREIGN KEY (id_civilizacion)
    REFERENCES civilizacion(id)
    ON DELETE CASCADE
);

-- Crear tabla para unidades
CREATE TABLE Unidades (
    id_civilizacion NUMBER(10) NOT NULL,
    unit_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 NOT NULL,
    unitGroup NUMBER(1) NOT NULL,
    armor NUMBER(10) DEFAULT 0,
    base_damage NUMBER(10) DEFAULT 0,
    experience NUMBER(10) DEFAULT 0,
    sanctified NUMBER(1) DEFAULT 0 CHECK (sanctified IN (0, 1)), 
    CONSTRAINT pk_unidades PRIMARY KEY (id_civilizacion, unit_id),
    CONSTRAINT fk_unidades FOREIGN KEY (id_civilizacion)
    REFERENCES civilizacion(id)
    ON DELETE CASCADE
);

CREATE TABLE Enemy (
    unitGroup NUMBER(1) NOT NULL,
    cantidad NUMBER(3),
    PRIMARY KEY (unitGroup)
);


-- Crear tabla para recursos enemigos
CREATE TABLE RecursosEnemy (
    madera NUMBER(10) DEFAULT 0,
    hierro NUMBER(10) DEFAULT 0,
    comida NUMBER(10) DEFAULT 0
);

-- Crear tabla para reportes generales de batalla
CREATE TABLE ReporteGeneralBatalla (
	numero NUMBER, 
    reporteCorto CLOB,
    reporteLargo CLOB
);

-- Crear tabla para tecnologías
CREATE TABLE Tecnologias (
    id_civilizacion NUMBER(10) PRIMARY KEY NOT NULL,
    ataque NUMBER(10) DEFAULT 0,
    defensa NUMBER(10) DEFAULT 0,
    CONSTRAINT fk_tecnologias FOREIGN KEY (id_civilizacion)
    REFERENCES civilizacion(id)
    ON DELETE CASCADE
);
